- name: Check if httpd is installed on RHEL servers
  hosts: webserver.integraoffice.lab
  become: yes
  vars:
    status: true
  tasks:
    - name: Check if httpd package is installed
      ansible.builtin.shell: rpm -q httpd
      register: httpd_check
      ignore_errors: yes

    - name: Set a value to the status variable
      ansible.builtin.set_fact:
        status: "{{ httpd_check.rc == 0 }}"

    - name: Report httpd installation status
      debug:
        msg: >
          {% if httpd_check.rc == 0 %}
            httpd is installed. ( STATUS = {{ status }} )
          {% else %}
            httpd is NOT installed. ( STATUS = {{ status }} )
          {% endif %}
      failed_when: status == false
 
   
